(function () {
  "use strict";
  const chat = document.getElementById("chat"), input = document.getElementById("input"), send = document.getElementById("send");
  const panel = document.getElementById("sessionsPanel"), list = document.getElementById("sessionsList"), title = document.getElementById("title");
  let current = null, sending = false, avatars = { user: "/img/user.jpg", cat: "/img/cat.png" };

  function esc(text) { const d = document.createElement("div"); d.textContent = text || ""; return d.innerHTML; }
  function add(role, text) { const row = document.createElement("article"); row.className = "mobile-msg " + role; const avatar = role === "user" ? avatars.user : avatars.cat; row.innerHTML = '<img class="mobile-avatar" src="' + avatar + '"><div class="mobile-bubble">' + esc(text) + "</div>"; chat.appendChild(row); chat.scrollTop = chat.scrollHeight; return row.querySelector(".mobile-bubble"); }
  function render(messages) { chat.innerHTML = ""; if (!messages.length) { chat.innerHTML = '<p class="mobile-empty">猫娘在这里，想聊点什么？</p>'; return; } messages.forEach(m => add(m.role, m.content)); }
  async function request(url, options) { const r = await fetch(url, options); if (r.status === 401) { location.replace("/m/login"); throw new Error("未登录"); } if (!r.ok) throw new Error((await r.json().catch(() => ({}))).detail || "请求失败"); return r.json(); }
  async function loadSessions() { const data = await request("/api/sessions"); list.innerHTML = ""; (data.sessions || []).forEach(s => { const b = document.createElement("button"); b.className = "mobile-session" + (s.id === current ? " active" : ""); b.innerHTML = esc(s.title || "新会话") + "<small>" + (s.count || 0) + " 条消息</small>"; b.onclick = () => select(s.id); list.appendChild(b); }); return data.current; }
  async function select(id) { const data = await request("/api/sessions/" + encodeURIComponent(id)); current = data.session.id; title.textContent = data.session.title || "新会话"; render(data.session.messages || []); panel.hidden = true; await loadSessions(); }
  async function fetchSSE(url, body, onEvent) { const response = await fetch(url, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body) }); if (response.status === 401) { location.replace("/m/login"); return; } if (!response.ok) throw new Error("发送失败"); const reader = response.body.getReader(), decoder = new TextDecoder(), state = { text:"" }; while (true) { const part = await reader.read(); if (part.done) break; state.text += decoder.decode(part.value, {stream:true}); let cut; while ((cut = state.text.indexOf("\n\n")) >= 0) { const raw = state.text.slice(0,cut); state.text = state.text.slice(cut+2); if (!raw.startsWith("data: ")) continue; onEvent(JSON.parse(raw.slice(6))); } } }
  async function submit(event) { event.preventDefault(); const text = input.value.trim(); if (!text || sending || !current) return; sending=true; send.disabled=true; input.value=""; if (chat.querySelector(".mobile-empty")) chat.innerHTML=""; add("user", text); const bubble=add("assistant", ""); try { await fetchSSE("/api/chat_response", {chatmassage:text, session_id:current}, evt => { if (evt.type === "delta") { bubble.textContent += evt.text; chat.scrollTop=chat.scrollHeight; } if (evt.type === "error") bubble.textContent = evt.detail || "本喵这次没接住消息，稍后再试喵。"; if (evt.type === "meta" && evt.session) title.textContent=evt.session.title || title.textContent; }); await loadSessions(); } catch (e) { bubble.textContent = "本喵这次没接住消息，稍后再试喵。"; } finally { sending=false; send.disabled=false; input.focus(); } }
  document.getElementById("sessionsButton").onclick = () => { panel.hidden = !panel.hidden; };
  document.getElementById("newButton").onclick = async () => { const data = await request("/api/sessions", {method:"POST"}); await select(data.current); };
  document.getElementById("composer").onsubmit=submit;
  input.addEventListener("input", () => { input.style.height="auto"; input.style.height=Math.min(input.scrollHeight,120)+"px"; });
  (async function init(){ try { const s = await request("/api/settings"); avatars={user:"/img/"+(s.user_avatar||"user.jpg"),cat:"/img/"+(s.cat_avatar||"cat.png")}; document.getElementById("subtitle").textContent=(s.pet_name||"猫娘")+" · 手机接入"; const id=await loadSessions(); await select(id); } catch(e) { chat.innerHTML='<p class="mobile-empty">连接失败，请回电脑检查手机接入设置。</p>'; } })();
}());
